version: '3.8'

services:
  api:
    build: ./
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/credi-discount
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: crediDiscount@1234
      POSTGRES_DB: credi_discount_development
  db-test:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: crediDiscountTest@1234
      POSTGRES_DB: credi_discount_test
